### ISSUE TITLE
打包后报错：ReferenceError: designForm is not defined

### ISSUE THREAD

**Issue by zhenzhenChange** [fuchengwei/vue-form-create#1]
打包后预览报错

[![c2nZn0.png](https://z3.ax1x.com/2021/04/15/c2nZn0.png)](https://imgtu.com/i/c2nZn0)

**Comment by fuchengwei** [comment]
可以把你的配置信息或者引入的代码发出来吗?

**Comment by zhenzhenChange** [comment]
我代码撤销了哈哈 😂，就是按照你例子里的`App.vue`和`main.js`，然后在`index.html`引入`acejs`。不过我是用`vite`。打包后本地预览不成功，用`cdn`的方式也是。

**Comment by fuchengwei** [comment]
目前不支持vite的

**Comment by zhenzhenChange** [comment]
好的，了解了
