### ISSUE TITLE
下载源码在本地编译不成功

### ISSUE THREAD

**Issue by zengjuemin** [fuchengwei/vue-form-create#10]
我在git 上下了源码之后，本地用
npm instll
npm run serve
之后界元素出不来，请问一下是什么原因，除了官网说的，还需要其它设置吗？
谢谢！

**Comment by fuchengwei** [comment]
不出来 可以试试把 public/index.html 中的 <script src="https://unpkg.com/ace-builds/src-noconflict/ace.js"></script> 这一句注释掉试试
