### ISSUE TITLE
表单属性修改后不生效

### ISSUE THREAD

**Issue by jackyyyy-dev** [fuchengwei/vue-form-create#11]
![image](https://user-images.githubusercontent.com/19222492/125726834-db9d2e8c-2b44-4454-b551-ff69a1fe44e9.png)

首次生成JSON后，第二次将JSON通过setJson方法赋值，表单并未发生更改 

如上图中的labelCol

版本：使用的demo地址 http://fuchengwei.gitee.io/vue-form-create/example/index.html

**Comment by jackyyyy-dev** [comment]
右侧“表单属性”下面 标签布局/span也还是3

**Comment by fuchengwei** [comment]
最新版本已经修复了 可以重新试一下
