### ISSUE TITLE
缺少自定义组件的方法

### ISSUE THREAD

**Issue by feianjun** [fuchengwei/vue-form-create#19]
大佬是不是什么时候有空加一下自定义的方法呢

**Comment by fuchengwei** [comment]
![image](https://user-images.githubusercontent.com/31444224/152743848-affa6302-f7cb-4e03-95f4-5f82e5a9138d.png)
最近在做基于 react 的表单设计器，基本都完成了。你说的这些功能都有还有很多新的特性。完成后会移植到 vue 中，请耐心等待
