### ISSUE TITLE
依赖问题导致运行报错

### ISSUE THREAD

**Issue by shandongtlb** [fuchengwei/vue-form-create#41]
ERROR in ./node_modules/vue-form-create/dist/formCreate.umd.min.js 1:3668-3682                                          
Module not found: Error: [CaseSensitivePathsPlugin] `C:\vue3\vue3-admin-front\node_modules\vue-form-create\node_modules\Vue\index.js` does not match the corresponding path on disk `vue`.
 @ ./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./node_modules/windicss-webpack-plugin/dist/loaders/windicss-template.js!./node_modules/unplugin/dist/webpack/loaders/transform.js??ruleSet[1].rules[46].use[0]!./src/views/xianlu/luru.vue?vue&type=script&lang=ts 3:0-51 6:4-20
 @ ./src/views/xianlu/luru.vue?vue&type=script&lang=ts 1:0-417 1:0-417 1:418-824 1:418-824
 @ ./src/views/xianlu/luru.vue 2:0-55 3:0-50 3:0-50 6:49-55
 @ ./src/router/asyncModules/xianlu.ts 3:32-65
 @ ./src/router/asyncModules/ sync \.ts$ ./xianlu.ts
 @ ./src/router/asyncModules/index.ts 6:21-56
 @ ./src/router/generator-router.tsx 22:0-65 90:24-48
 @ ./src/store/modules/user.ts 13:0-67 117:32-54
 @ ./src/router/router-guards.ts 7:0-52 22:24-36
 @ ./src/router/index.ts 7:0-53 42:10-28
 @ ./src/main.ts 93:0-39 131:17-28

webpack compiled with 1 error

请大佬看看，我是没有装什么依赖项吗

**Comment by fuchengwei** [comment]
你可以加一下我微信 项目发来我看看 fuchengwei325795

**Comment by fuchengwei** [comment]
最新版本 1.2.10 以解决

**Comment by shandongtlb** [comment]
谢谢大佬，成功了！
