### ISSUE TITLE
img-upload组件出现排版错误

### ISSUE THREAD

**Issue by shandongtlb** [fuchengwei/vue-form-create#42]
如图
![image](https://user-images.githubusercontent.com/40312509/169704279-fdc2e2bb-c033-49a2-b3ee-61cce7755246.png)
不知道什么情况，这个扁了。。。
附源码，求大佬帮忙看看嘻嘻嘻

https://github.com/shandongtlb/vue.git

另外，对于392行的  state.generateFormRef  会报错  Object is possibly 'null'

**Comment by fuchengwei** [comment]
upload 扁了你检查一下样式应该是被你外部样式修改了 state.generateFormRef为 null 你可以试试单独用 ref 声明一个变量来引用

**Comment by shandongtlb** [comment]
好的，谢谢大佬指点！
