### ISSUE TITLE
引入报错,报错信息如下

### ISSUE THREAD

**Issue by zhenzenzen** [fuchengwei/vue-form-create#44]
为啥在main.ts引入后,报错
main.ts:51 Uncaught (in promise) TypeError: Object(...) is not a function at Module.643d

怎么解决这个问题啊?

项目是vue3.0+vite+ant-design 的

**Comment by fuchengwei** [comment]
可以把你的项目发邮件给我 我看一下 1572060320@qq.com

**Comment by fuchengwei** [comment]
看了你的项目 我把你项目中的其余依赖删除 重新安装 node_modules 就好了 具体是哪个依赖导致冲突需要你自己一个一个排查一下了
