### ISSUE TITLE
使用富文本报错卡死问题

### ISSUE THREAD

**Issue by helloZh4n** [fuchengwei/vue-form-create#59]
VM27428:1 Uncaught (in promise) SyntaxError: "undefined" is not valid JSON

**Comment by fuchengwei** [comment]
麻烦把配置的 JSON 贴出来 我复现一下

**Comment by helloZh4n** [comment]
还有提一个问题 就是全局样式注入的时候 是否可以考虑自定义类去包一层/这样全局注入改变了很多样式 特别是滚动条+字体

**Comment by fuchengwei** [comment]
已修复，试一下最新版本。并且滚动条样式已经修复了。

**Comment by helloZh4n** [comment]
好的 谢谢 我看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fuchengwei/vue-form-create"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fuchengwei/vue-form-create] 使用富文本报错卡死问题 (Issue #59)





 
Closed #59 as completed.

**Comment by helloZh4n** [comment]
您好 记得发布一下npm包仓库


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fuchengwei/vue-form-create"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fuchengwei/vue-form-create] 使用富文本报错卡死问题 (Issue #59)





 
Closed #59 as completed.

**Comment by fuchengwei** [comment]
已经发布了

**Comment by helloZh4n** [comment]
你看一下 是不是发布后没更新吗
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fuchengwei/vue-form-create"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fuchengwei/vue-form-create] 使用富文本报错卡死问题 (Issue #59)





 
已经发布了

**Comment by fuchengwei** [comment]
打完包 忘记发布 npm 了 你现在试试
