### ISSUE TITLE
插件引入报错Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by kennsand** [fuchengwei/vue-form-create#7]
![image](https://user-images.githubusercontent.com/22880635/120448821-848d7e00-c3be-11eb-9440-04390c275fd4.png)

**Comment by fuchengwei** [comment]
可以说一下你的环境吗 vue版本

**Comment by kennsand** [comment]
> 可以说一下你的环境吗 vue版本

"vue": "^2.6.11"

**Comment by fuchengwei** [comment]
这个是vue3.0的插件

**Comment by fangpeng1991** [comment]
使用的 vue3,但有同样的问题

"dependencies": {
    "@element-plus/icons": "^0.0.11",
    "axios": "0.21.1",
    "bootstrap": "5.0.2",
    "bootstrap-vue": "^2.21.2",
    "bpmn-js": "^8.7.1",
    "bpmn-js-properties-panel": "^0.44.0",
    "camunda-bpmn-js": "^0.9.3",
    "camunda-bpmn-moddle": "^5.1.2",
    "core-js": "3.15.2",
    "echarts-stat": "^1.2.0",
    "element-plus": "^1.0.2-beta.54",
    "eslint-import-resolver-typescript": "^2.4.0",
    "form-gen-parser": "^1.0.3",
    "jquery": "^3.6.0",
    "js-cookie": "^3.0.0",
    "normalize.css": "^8.0.1",
    "path-to-regexp": "^0.1.7",
    "view-design": "4.6.1",
    "vue": "3.1.4",
    "vue-cropperjs": "^5.0.0",
    "vue-echarts": "^6.0.0-rc.6",
    "vue-form-create": "^1.2.5",
    "vue-i18n": "^8.25.0",
    "vue-router": "4.0.10",
    "vuex": "4.0.2",
    "wangeditor": "^4.7.5",
    "webpack": "^4.46.0",
    "xcrud": "^0.4.19",
    "xlsx": "^0.17.4"
  },

**Comment by fuchengwei** [comment]
> 

看一下引入是否按照文档的要求进行引入的

**Comment by 7polo** [comment]
问题解决了吗， 同样遇到这个问题， vue3 + vite

**Comment by fuchengwei** [comment]
> 

看下你项目中别的什么插件依赖了 vue2 的版本
